// <auto-generated />
using System;
using HotelGuru.DataContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelGuru.DataContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250521153639_RegisterMigration")]
    partial class RegisterMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoglalasPluszSzolgaltatas", b =>
                {
                    b.Property<int>("FoglalasokId")
                        .HasColumnType("int");

                    b.Property<int>("PluszSzolgaltatasokId")
                        .HasColumnType("int");

                    b.HasKey("FoglalasokId", "PluszSzolgaltatasokId");

                    b.HasIndex("PluszSzolgaltatasokId");

                    b.ToTable("FoglalasPluszSzolgaltatas", (string)null);
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Felhasznalonev")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JelszoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeljesNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Felhasznalonev")
                        .IsUnique();

                    b.ToTable("Felhasznalok");

                    b.HasDiscriminator().HasValue("Felhasznalo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Foglalas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ErkezesDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LemondasiIdo")
                        .HasColumnType("datetime2");

                    b.Property<int>("SzobaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TavozasDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendegId")
                        .HasColumnType("int");

                    b.Property<bool>("Visszaigazolva")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SzobaId");

                    b.HasIndex("VendegId");

                    b.ToTable("Foglalasok");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.PluszSzolgaltatas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PluszSzolgaltatasok");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Szoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Felszereltseg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FerohelyekSzama")
                        .HasColumnType("int");

                    b.Property<bool>("Foglalhato")
                        .HasColumnType("bit");

                    b.Property<string>("Szobaszam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Szobak");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Adminisztrator", b =>
                {
                    b.HasBaseType("HotelGuru.DataContext.Entities.Felhasznalo");

                    b.HasDiscriminator().HasValue("Adminisztrator");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Recepcios", b =>
                {
                    b.HasBaseType("HotelGuru.DataContext.Entities.Felhasznalo");

                    b.HasDiscriminator().HasValue("Recepcios");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Vendeg", b =>
                {
                    b.HasBaseType("HotelGuru.DataContext.Entities.Felhasznalo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonszam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Vendeg");
                });

            modelBuilder.Entity("FoglalasPluszSzolgaltatas", b =>
                {
                    b.HasOne("HotelGuru.DataContext.Entities.Foglalas", null)
                        .WithMany()
                        .HasForeignKey("FoglalasokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelGuru.DataContext.Entities.PluszSzolgaltatas", null)
                        .WithMany()
                        .HasForeignKey("PluszSzolgaltatasokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Foglalas", b =>
                {
                    b.HasOne("HotelGuru.DataContext.Entities.Szoba", "Szoba")
                        .WithMany("Foglalasok")
                        .HasForeignKey("SzobaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelGuru.DataContext.Entities.Vendeg", "Vendeg")
                        .WithMany("Foglalasok")
                        .HasForeignKey("VendegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Szoba");

                    b.Navigation("Vendeg");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Szoba", b =>
                {
                    b.Navigation("Foglalasok");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Vendeg", b =>
                {
                    b.Navigation("Foglalasok");
                });
#pragma warning restore 612, 618
        }
    }
}
